using Application.Auth;
using Application.Common.Interfaces.Auth;
using Application.Dto;
using Domain.Common.Exceptions;
using Domain.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace Application.Services.Auth
{
    public class AuthService : IAuthService
    {

        private readonly IUserRepository _userRepository;
        private readonly JwtConfig _jwtConfig;

        public AuthService(IUserRepository authRepository, IOptionsMonitor<JwtConfig> optionsMonitor)
        {
            _userRepository = authRepository;
            _jwtConfig = optionsMonitor.CurrentValue;
        }

        public async Task<AuthResponse> Login(UserLoginRequestDto user)
        {
            if (await _userRepository.UserExists(user.Email))
            {
                var existingUser = await _userRepository.FindByEmail(user.Email);

                if (await _userRepository.CheckCredentials(existingUser, user.Password))
                {
                    var jwtToken = GenerateJwtToken(existingUser);

                    return new AuthResponse()
                    {
                        Result = true,
                        Token = jwtToken
                    };
                }

                
                throw new ExceptionHandler(
                    HttpStatusCode.Unauthorized, 
                    new List<string>() { 
                        "El usuario/password son incorrectos." 
                    }
                );
            }

            throw new ExceptionHandler(
                HttpStatusCode.NotFound,
                new List<string>() {
                    "El usuario no se encuentra en el sistema."
                }
            );
        }

        public async Task<AuthResponse> Register(UserRegisterRequestDto user)
        {

            if (await _userRepository.UserExists(user.Email))
            {
                return new AuthResponse()
                {
                    Result = false,
                    Errors = new List<string>(){
                        "Email ya existe"
                    }
                };
            }

            var newUser = new User() { Email = user.Email, UserName = user.Email };
            var isCreated = await _userRepository.CreateUser(newUser, user.Password);

            if (isCreated.Succeeded)
            {
                var jwtToken = GenerateJwtToken(newUser);

                return new AuthResponse()
                {
                    Result = true,
                    Token = jwtToken
                };
            }

            throw new ExceptionHandler(
                HttpStatusCode.InternalServerError,
                isCreated.Errors.Select(x => x.Description).ToList()
            );
        }

        private string GenerateJwtToken(IdentityUser user)
        {
            // Now its ime to define the jwt token which will be responsible of creating our tokens
            var jwtTokenHandler = new JwtSecurityTokenHandler();

            // We get our secret from the appsettings
            var key = Encoding.ASCII.GetBytes(_jwtConfig.Secret);

            // we define our token descriptor
            // We need to utilise claims which are properties in our token which gives information about the token
            // which belong to the specific user who it belongs to
            // so it could contain their id, name, email the good part is that these information
            // are generated by our server and identity framework which is valid and trusted
            var tokenDescriptor = new SecurityTokenDescriptor
            {
                Subject = new ClaimsIdentity(new[]
                {
                new Claim("Id", user.Id),
                new Claim(JwtRegisteredClaimNames.Sub, user.Email),
                new Claim(JwtRegisteredClaimNames.Email, user.Email),
                // the JTI is used for our refresh token which we will be convering in the next video
                new Claim(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString())
            }),
                // the life span of the token needs to be shorter and utilise refresh token to keep the user signedin
                // but since this is a demo app we can extend it to fit our current need
                Expires = DateTime.UtcNow.AddHours(6),
                // here we are adding the encryption alogorithim information which will be used to decrypt our token
                SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(key), SecurityAlgorithms.HmacSha512Signature)
            };

            var token = jwtTokenHandler.CreateToken(tokenDescriptor);

            var jwtToken = jwtTokenHandler.WriteToken(token);

            return jwtToken;
        }
    }
}
